# Generated by Django 3.1.3 on 2020-11-17 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Physics', 'Physics'), ('Art', 'Art'), ('Politics', 'Politics'), ('Music', 'Music'), ('Electronics', 'Electronics'), ('Mathematics', 'Mathematics'), ('Geography', 'Geography'), ('History', 'History'), ('Other', 'Other')], default='Other', max_length=20)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
